# runtime: nodejs10

# instance_class: F2

# env_variables:
#   BUCKET_NAME: "example-gcs-bucket"

# handlers:
# - url: /stylesheets
#   static_dir: stylesheets

# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto

runtime: nodejs
env: flex

network:
  session_affinity: true
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
